services:
  userauth:
    build: ./UserAuth-Service
    ports:
      - "7002:7002"
    environment:
      DB_URL: mongodb+srv://hirunipraveesha18:N3L0BtXaci7arCGW@cluster0.d46wa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      auramart-network:
  
  cart:
    build: ./Shopping-cart
    ports:
      - "7001:7001"
    environment:
      DB_URL: mongodb+srv://hirunipraveesha18:N3L0BtXaci7arCGW@cluster0.d46wa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      auramart-network:
  
  product:
    build: ./Product-Service
    ports:
      - "7005:7005"
    environment:
      DB_URL: mongodb+srv://hirunipraveesha18:N3L0BtXaci7arCGW@cluster0.d46wa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      auramart-network:

  order:
    build: ./Order-Service
    ports:
      - "7003:7003"
    environment:
      DB_URL: mongodb+srv://hirunipraveesha18:N3L0BtXaci7arCGW@cluster0.d46wa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      auramart-network:
  
   
  admin:
    build: ./Admin-Service
    ports:
      - "7004:7004"
    environment:
      DB_URL: mongodb+srv://hirunipraveesha18:N3L0BtXaci7arCGW@cluster0.d46wa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    networks:
      auramart-network:

  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - AURAMART-Microservice:/data/db
    networks:
      auramart-network:

networks:
  auramart-network:

volumes:
  AURAMART-Microservice: